#
# THANKS FOR USING DISCORDAUTH!
#
# Notes: some settings need to be changed, there are noted by "#*"

# BungeeCord enable core features by default, only enable for one server network
core: false
#* Secret for messaging security, change it and put the same for all your servers
secret: unsafe_key
# Language file that will be used (can be custom file name in DiscordAuth/resources folder)
# Can be "en_EN" or "fr_FR"
language: en_EN