#
# THANKS FOR USING DISCORDAUTH!
#
# Notes: some settings need to be changed, there are noted by "#*"

both:
  #* Secret for messaging security, change it and put the same for all your servers
  secret: unsafe_key
  # Language file that will be used (can be custom file name in DiscordAuth/resources folder)
  # Can be "en_EN" or "fr_FR"
  language: en_EN

# Settings for core server only
core:
  enable: false # BungeeCord enable core features by default
  mysql:
    enable: false
    host: 0.0.0.0
    port: 3306
    user: username
    password: password
    database: database_name
  session_duration: 3600
  discord:
    #* Put here your bot token
    token: token
    # Disable discord part of the plugin, but keep server's safety and account management
    only_safety: false
    # Add logo to private messages response
    logo:
      enable: false
      url: null
    # Set bot status here
    activity:
      enable: true
      # Can be PLAYING, STREAMING, LISTENING or WATCHING
      type: PLAYING
      text: DiscordAuth V3.0!
      # Only for streaming
      url: null

# Settings for game server only
game:
  # Spawn point settings
  spawnpoint:
    # Enable first time spawn point
    first_time_tp: false
    # Tp player at spawn point on login
    tp_on_login: false
    # Respawn settings
    respawn:
      # Tp player to spawn point if his die
      enable: false
      # If enabled, player will be tp at death even if his had a bed respawn
      even_with_bed: false
    # Spawn point location settings
    infos:
      world_name: world
      x: 0
      y: 80
      z: 0
      facing:
        pitch: 0
        yaw: 0
