author: Xen0Xys
name: DiscordAuth
version: 3.0.0
api-version: 1.19
main: fr.xen0xys.discordauth.DiscordAuth
database: true

commands:
  discordauth:
    permission: discordauth.discordauth
    aliases: [da]
    usage: /discordauth <reload>
  account:
    permission: discordauth.account
    usage: /account manage|delete
  login:
    aliases: [l]
    permission: discordauth.login
  logout:
    permission: discordauth.logout
  forcelogin:
    permission: discordauth.forcelogin
    usage: /forcelogin <minecraftName>

permissions:
  discordauth.*:
    description: Gives access to all DiscordAuth commands
    children:
      discordauth.discordauth: true
      discordauth.account: true
      discordauth.login: true
      discordauth.logout: true
      discordauth.forcelogin: true
  discordauth.discordauth:
    default: op
  discordauth.account:
    default: true
  discordauth.login:
    default: true
  discordauth.logout:
    default: true
  discordauth.forcelogin:
    default: op