#
# THANKS FOR USING DISCORDAUTH!
#
# Notes: some settings need to be changed, there are noted by "#*"

# Settings for game server only
spawnpoint:
  # Enable packet time spawn point
  first_time_tp: false
  # Tp player at spawn point on login
  tp_on_login: false
  # Respawn settings
  respawn:
    # Tp player to spawn point if his die
    enable: false
    # If enabled, player will be tp at death even if his had a bed respawn
    even_with_bed: false
  # Spawn point location settings
  infos:
    world_name: world
    x: 0
    y: 80
    z: 0
    facing:
      pitch: 0
      yaw: 0
